--all object in database
select * from INFORMATION_SCHEMA.TABLES

--all column in database
select * from INFORMATION_SCHEMA.COLUMNS

--all countries our customers are from
select distinct country from Gold.dim_customers


--all categories 'the major divisions'
select distinct category, subcategory, product_name from Gold.dim_products
order by 1,2,3

--find the date of the first and last order
select 
min(order_date) as first_date, 
MAX(order_date) as last_date,
DATEDIFF(year, min(order_date), MAX(order_date)) as order_range_years
from Gold.fact_sales

--find youngest and oldest customer
select 
min(Brithdate) as oldest,
datediff(year, min(Brithdate), getdate()) as oldest_age,
max(Brithdate) as youngest,
datediff(year, max(Brithdate) , GETDATE()) as youngest_age from Gold.dim_customers


--Find the Total Sales
select sum(sales_amount) as total_sales from Gold.fact_sales
--Find how many items are sold
select sum(quantity) as total_items_sold from Gold.fact_sales
--Find the average selling price
select AVG(sls_price) as average_price from Gold.fact_sales
--Find the Total number of Orders
select count(distinct order_number) as total_sales from Gold.fact_sales
--Find the total number of products
select count(product_key) as total_product from Gold.dim_products
--Find the total number of customers
select count(customer_key) as total_product from Gold.dim_customers
--Find the total number of customers that has placed an order
select count(distinct Customer_id) as total_product from Gold.fact_sales

--generate a report of all key metrics of the busness
select 'Total sales' as measure_name, sum(sales_amount) as total_sales from Gold.fact_sales
union all
select 'Total item sold' ,sum(quantity) as total_items_sold from Gold.fact_sales
union all
select 'Average selling price', AVG(sls_price) as average_price from Gold.fact_sales
union all
select 'Total number of Orders', count(distinct order_number) as total_sales from Gold.fact_sales
union all
select 'Total number of products', count(product_key) as total_product from Gold.dim_products
union all
select 'Total number of customers', count(customer_key) as total_product from Gold.dim_customers
union all
select 'Total number of customers that has placed an order', count(distinct Customer_id) as total_product from Gold.fact_sales


--Find total customers by countries
select country, count(customer_key) as total_customers from Gold.dim_customers
group by Country
order by total_customers desc
--Find total customers by gender
select gender, count(customer_key) as total_customers from Gold.dim_customers
group by Gender
order by total_customers desc
--Find total products by category
select category, count(product_key) as total_products from Gold.dim_products
group by category
order by total_products desc
--What is the average costs in each category?
select category, AVG(product_cost) as avg_cost_products from Gold.dim_products
group by category
order by avg_cost_products desc
--What is the total revenue generated for each category?
select 
p.category,
sum(f.sales_amount) as total_revenue
from Gold.fact_sales f
left join Gold.dim_products p
on p.product_number=f.product_number
group by p.category
order by total_revenue desc
--Find total revenue is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.Customer_id = f.Customer_id
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC
--What is the distribution of sold items across countries?
SELECT
c.country, 
SUM(f.sales_amount) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.Customer_id = f.Customer_id
GROUP BY
c.Country
ORDER BY total_items_sold DESC



--Which 5 products generate the highest revenue?

select top 5
p.product_name,
sum(f.sales_amount) as total_revenue
from Gold.fact_sales f
left join Gold.dim_products p
on p.product_number=f.product_number
group by p.product_name
order by total_revenue desc

--What are the 5 worst-performing products in terms of sales?

select top 5
p.product_name,
sum(f.sales_amount) as total_revenue
from Gold.fact_sales f
left join Gold.dim_products p
on p.product_number=f.product_number
group by p.product_name
order by total_revenue

--Find the top 10 customers who have generated the highest revenue

select top 10
c.Customer_id,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from Gold.fact_sales f
left join Gold.dim_customers c
on c.Customer_id=f.Customer_id
group by c.Customer_id,
c.first_name,
c.last_name
order by total_revenue desc

--The 3 customers with the fewest orders placed

select top 3
c.Customer_id,
c.first_name,
c.last_name,
count(distinct order_number) as total_orders
from Gold.fact_sales f
left join Gold.dim_customers c
on c.Customer_id=f.Customer_id
group by c.Customer_id,
c.first_name,
c.last_name
order by total_orders
